# <workflow-name>.yml

name: Run Recurring Venmo

on:
  schedule:
    # 5/6pm EDT on the 14th of the month.
    - cron: "0 10 14 * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install venmo-api
      - name: Run script 
        # https://pipenv.pypa.io/en/latest/advanced/#automatic-loading-of-env; this is somewhat silly but I wanted to finish quick
        run: |
          python main.py
        env:
          VENMO_ACCESS_TOKEN: ${{ secrets.VENMO_ACCESS_TOKEN }}
          SREYA: ${{ vars.SREYA}}
          JERRY: ${{ vars.JERRY}}
          SAHIL: ${{ vars.SAHIL}}
          ROHAN: ${{ vars.ROHAN}}
          PRACHI: ${{ vars.PRACHI}}
          JAKE: ${{ vars.JAKE}}
          SARAH: ${{ vars.SARAH}}